/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.optaplanner.examples.driverallot.solver;
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;

import org.optaplanner.examples.driverallot.domain.DriverAllot;
import org.optaplanner.examples.driverallot.domain.Driver;
import org.optaplanner.examples.driverallot.domain.RouteTrip;
import org.optaplanner.examples.driverallot.domain.solver.RouteTripConflict;
import org.optaplanner.examples.driverallot.domain.solver.RouteTripDistance;
import org.optaplanner.examples.driverallot.domain.solver.DriverRouteTripDistance;

global HardSoftScoreHolder scoreHolder;

// ############################################################################
// Hard constraints
// ############################################################################

rule "driverTimeMatches"
	when
		$driver : Driver($timeIn : timeIn, $timeOut : timeOut)
		RouteTrip(
			driver == $driver && 
			$timeStart : timeStart &&
			$timeEnd : timeEnd &&
			(
				timeStart < $timeIn || 
				timeEnd > $timeOut
			)
		)
	then
		scoreHolder.addHardConstraintMatch(kcontext, -5);
end

rule "oneTripAtATime"
	when
		$routeTripConflict : RouteTripConflict(
			$leftRouteTripId : leftRouteTrip.id,
			$rightRouteTripId : rightRouteTrip.id
		)
		$leftRouteTrip : RouteTrip(
			id == $leftRouteTripId,
			driver != null,
			$leftRouteTripDriver : driver,
			$leftRouteTriptimeStart : timeStart,
			$leftRouteTriptimeEnd : timeEnd
		)
		$rightRouteTrip : RouteTrip(
			id == $rightRouteTripId,
			driver != null,
			driver == $leftRouteTripDriver,
			//driver.id != 0,
			driver.type != Driver.UNIVERSAL_DRIVER,
			$rightRouteTriptimeStart : timeStart,
			$rightRouteTriptimeEnd : timeEnd
		)
	then
		scoreHolder.addHardConstraintMatch(kcontext, -5);
		//System.out.println("oneTripAtATime " + $leftRouteTripDriver + " " + $leftRouteTrip + " " + $leftRouteTriptimeStart + "-" + $leftRouteTriptimeEnd + "   " + $rightRouteTriptimeStart + "-" + $rightRouteTriptimeEnd + " " + $rightRouteTrip);
end

rule "enoughTimeBetweenTrips"
	when
		$previousRouteTrip : RouteTrip(
			$driver : driver,
			driver != null,
			$endTime : timeEnd
		)
		$routeTrip : RouteTrip(
			$driver == driver,
			$startTime : timeStart,
			id != $previousRouteTrip.id
		)
		$firstRouteTrip : Number(intValue == $startTime) from accumulate(
            RouteTrip(
                $driver == driver,
                $timeStart : timeStart,
                $timeStart >= $endTime
            ),
            min($timeStart)
        )
		$routeTripDistance : RouteTripDistance (
			leftRouteTrip == $previousRouteTrip,
			rightRouteTrip == $routeTrip,
			possibleToAttendBoth == false
		)
	then
		scoreHolder.addHardConstraintMatch(kcontext, -5);
		//System.out.println("enoughTimeBetweenTrips " + $previousRouteTrip + " " + $routeTrip);
end

// ############################################################################
// Soft constraints
// ############################################################################


rule "driverRankHigh"
	when
		$driver : Driver($rank : rank)
        RouteTrip($driver == driver)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, - $rank);
        //System.out.println("driverRankHigh " + $driver + " " + $rank);
end

rule "routeRankHigh"
	when
		$driver : Driver(
			//id != 0,
			type != Driver.UNIVERSAL_DRIVER,
			$driverRank : rank
		)
        $routeTrip : RouteTrip(
			driver == $driver,
			$routeRank : rank
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, - ($routeRank * $driverRank));
		//System.out.println("routeRankHigh " + $routeTrip + " " + $driver + " " + ($routeRank * $driverRank));
end

/*rule "noTripDriverPenalty"
	when
		$driver : Driver(
			id != 0,
			$driverRank : rank
		)
		not (exists RouteTrip(driver == $driver))
	then
		scoreHolder.addSoftConstraintMatch(kcontext, - ($driverRank*2));
		//System.out.println("noTripDriverPenalty " + $driver + " " + $driverRank);
end*/

rule "firstTripDriverProximity"
	when
		$routeTrip : RouteTrip(
			$driver : driver,
			driver != null,
			$firstTimeStart : timeStart
		)
		$firstRouteTrip : Number(intValue == $firstTimeStart) from accumulate(
            RouteTrip(
                $driver == driver,
                $timeStart : timeStart),
            min($timeStart)
        )
		$driverRouteTripDistance : DriverRouteTripDistance (
			driver == $driver,
			routeTrip == $routeTrip,
			$distanceToStartInMeters : timeToStartInMinutes//InMeters
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -(int)$distanceToStartInMeters);
		//System.out.println("firstTripDriverProximity " + $driver + " " + $routeTrip + " " + $distanceToStartInMeters);
end

rule "twoTripsStartEndProximity"
	when
		$previousRouteTrip : RouteTrip(
			$driver : driver,
			driver != null,
			$endTime : timeEnd
		)
		$routeTrip : RouteTrip(
			$driver == driver,
			$startTime : timeStart,
			id != $previousRouteTrip.id
		)
		$firstRouteTrip : Number(intValue == $startTime) from accumulate(
            RouteTrip(
                $driver == driver,
                $timeStart : timeStart,
                $timeStart >= $endTime
            ),
            min($timeStart)
        )
		$routeTripDistance : RouteTripDistance (
			leftRouteTrip == $previousRouteTrip,
			rightRouteTrip == $routeTrip,
			$distanceInMeters : timeInMinutes//InMeters
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -(int)$distanceInMeters);
		//System.out.println("twoTripsStartEndProximity " + $previousRouteTrip + " " + $routeTrip + " " + $distanceInMeters);
		scoreHolder.addSoftConstraintMatch(kcontext, -($startTime - $endTime));
		//System.out.println("twoTripsStartEndTimeProximity " + $previousRouteTrip + " " + $routeTrip + " " + ($startTime - $endTime));
end

rule "lastTripDriverProximity"
	when
		$routeTrip : RouteTrip(
			$driver : driver,
			driver !=null,
			$lastTimeEnd : timeEnd
		)
		$lastRouteTrip : Number(intValue == $lastTimeEnd) from accumulate(
            RouteTrip(
                $driver == driver,
                $timeEnd : timeEnd),
            max($timeEnd)
        )
		$driverRouteTripDistance : DriverRouteTripDistance (
			driver == $driver,
			routeTrip == $routeTrip,
			$distanceToEndInMeters : timeToEndInMinutes//InMeters
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -(int)$distanceToEndInMeters);
		//System.out.println("lastTripDriverProximity " + $driver + " " + $routeTrip + " " + $distanceToEndInMeters);
end




/*rule "twoTripsStartEndTimeProximity"
	when
		$routeTrip : RouteTrip(
			previousTrip != null,
			$previousTrip : previousTrip,
			$routeTripStartTime : timeStart,
			$previousRouteTripEndTime : previousTrip.timeEnd
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -($routeTripStartTime - $previousRouteTripEndTime)/(60*10));
		System.out.println("twoTripsStartEndTimeProximity " + ($routeTripStartTime - $previousRouteTripEndTime)/(60*10));
end*/



/*rule "firstTripDriverProximity"
	when
		$routeTrip : RouteTrip(
			$driver : driver,
			previousTrip == null
		)
		$driverRouteTripDistance : DriverRouteTripDistance (
			driver == $driver,
			routeTrip == $routeTrip,
			$distanceToStartInMeters : distanceToStart//InMeters
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -(int)$distanceToStartInMeters);
		System.out.println("firstTripDriverProximity " + $driver + " " + $routeTrip + " " + $distanceToStartInMeters);
end*/

/*rule "twoTripsStartEndProximity"
	when
		$routeTrip : RouteTrip(
			previousTrip != null,
			$previousTrip : previousTrip
		)
		$routeTripDistance : RouteTripDistance (
			leftRouteTrip == $previousTrip,
			rightRouteTrip == $routeTrip,
			$distanceInMeters : distance//InMeters
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -(int)$distanceInMeters);
		System.out.println("twoTripsStartEndProximity " + $distanceInMeters);
end*/

/*rule "lastTripDriverProximity"
	when
		$routeTrip : RouteTrip(
			$driver : driver,
			nextTrip == null
		)
		$driverRouteTripDistance : DriverRouteTripDistance (
			driver == $driver,
			routeTrip == $routeTrip,
			$distanceToEndInMeters : distanceToEnd//InMeters
		)
	then
		scoreHolder.addSoftConstraintMatch(kcontext, -(int)$distanceToEndInMeters);
		System.out.println("lastTripDriverProximity " + $driver + " " + $routeTrip + " " + $distanceToEndInMeters);
end*/